Main section
maciekkwiet/Camp_HTML-CSS pull request #14
Opened 2020-11-25 10:58 UTC by rafenoxu

2020-11-26 21:24 UTC, maciekkwiet requested changes
Super! Nie mam większych zastrzeżeń, jedynie ten plik z reset.css nie wydaje mi się konieczny, takie pliki niestety wprowadzają trochę zamieszania w projekcie rzeczej czegoś takiego się nie stosuje, poza tym extra! Zróbmy tego drugiego taska szybko i idźmy do JS, brawo!

2020-11-26 21:24 UTC, maciekkwiet commented on styles/scss/_variables.scss
> +$navbar-height: 95px;
Wyodrębniony plik ze zmiennymi, super!

2020-11-27 15:16 UTC, KlaraGajaszek requested changes
Super robota, zrób pare poprawek proszę to kod będzie  spójny z pozostałą częścią zespołu :)

2020-11-27 15:16 UTC, KlaraGajaszek commented on styles/scss/components/body-header.scss
> +@import '../reset';
nazwij ten plik  bodyHeaderStyles.scss proszę :)

2020-11-27 15:16 UTC, KlaraGajaszek commented on styles/scss/components/body-header.scss
> +.body-header {
jak możesz to  style zapisuj za pomocą camelCase bodyHeader wtedy nasz kod będzie bardziej spójny i czytelny z innymi branchami :)

2020-11-27 22:47 UTC, KlaraGajaszek approved these changes

2020-11-28 13:06 UTC, rafenoxu commented on styles/scss/_variables.scss
> +$navbar-height: 95px;
Mam usunąć reset.css przed mergem?

2020-11-28 13:31 UTC, merged