Navigation section
maciekkwiet/Camp_HTML-CSS pull request #19
Opened 2020-11-26 22:57 UTC by wojaneta

closes #1

2020-11-27 14:44 UTC, KlaraGajaszek requested changes
Good job 🥇 Parę drobnych uwag ode mnie :)

2020-11-27 14:44 UTC, KlaraGajaszek commented on styles/nav-style.css
> +body {
Moim zdaniem lepiej będzie gdy plik nazwiemy za pomocą camelCasa  (navStyle) ? Co myślisz ?

2020-11-27 14:44 UTC, KlaraGajaszek commented on styles/nav-style.css
> +@media only screen and (max-width: 600px) {
Może lepiej będzie jak w widoku mobilnym zostawimy wyświetlanie jako row, ale nie będziemy wyświetlać logo i pozbedziemy sie "marginesów" z prawej i  lewej strony wtedy będzie bardziej user friendly  :)

2020-11-27 18:46 UTC, maciekkwiet requested changes
Jak dla mnie super!
Możemy poprawić ten komentarz z widokiem mobilnym i będziemy mergować :D

2020-11-27 18:46 UTC, maciekkwiet commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet">
Tylko jedna waga, extra!

2020-11-28 20:31 UTC, maciekkwiet approved these changes

2020-11-29 18:02 UTC, KlaraGajaszek approved these changes

2020-11-29 20:00 UTC, merged