Navigation hover
maciekkwiet/Camp_HTML-CSS pull request #36
Opened 2020-11-30 19:05 UTC by wojaneta

closes #22

2020-11-30 22:17 UTC, maciekkwiet requested changes
Wow! Naprawdę mega! Ale nie byłbym trochę sobą gdybym może lekko nie ponarzekał ;p 
1. Może spróbujmy ten dropdown przenieść do prawej strony a nie na środku, dzięki temu pozostanie miejsce na obrazek do lewej, to chyba by lepiej wyglądało
2.  Maga by było gdybyśmy dali rade w momencie wysuwania dropdownu, nie wpływać na sekcję niżej(bez jej przesuwania) w razie problemów z tym, pisz śmiało to postaram się coś pomóc :D
Co do samego kodu nie ma zastrzeżeń, jest extra!

2020-11-30 22:18 UTC, KlaraGajaszek commented on styles/nav-style.css
>      background-color: #E1E1E1;
usuńmy kolor w body, bo wtedy wplywamy na cala strone a zalezy nam tylko na header

2020-11-30 22:30 UTC, KlaraGajaszek requested changes

2020-11-30 22:30 UTC, KlaraGajaszek commented on styles/nav-style.css
> +nav div.dropdown div.logo {
zmniejszy ten margines zeby Logo było bardzie z lewej strony. Podobnie jak tutaj https://www.reserved.com/pl/pl/

2020-11-30 22:30 UTC, KlaraGajaszek commented on styles/nav-style.css
>  @media only screen and (max-width: 600px) {
w mobilce przenieśmy dropdowna maxymalnie w lewo i usuńmy dolny margines

2020-11-30 22:30 UTC, KlaraGajaszek commented on styles/nav-style.css
> +nav div.dropdown {
margin możemy trochę zmniejszyc

2020-12-01 19:26 UTC, maciekkwiet approved these changes
Jak dla mnie mega! Możesz spróbowac dodać to co napisałem i zobaczyć czy na twoje oko by było trochę lepiej i wybrać lepszą wersje :D
Ew. opcjonalnie powalczyć z transition na rozwijanie dropdowna, ale to już jakbyś chciała to naprawdę dopieścić 🥇

2020-12-01 19:26 UTC, maciekkwiet commented on styles/nav-style.css
>      }
Może dodajmy do tej sekcji jeszcze coś mniej więcej takiego:
        top: 78px;
        border-radius: 10px;
Bedzie troszeczkę chyba lepiej dzięki temu wyglądało :D

2020-12-02 19:09 UTC, KlaraGajaszek approved these changes

2020-12-02 20:39 UTC, merged